package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
)

// UseGeneratedIDForUnknown behaves like stringplanmodifier.UseNonNullStateForUnknown,
// except it also treats an empty string in state the same as null.
//
// Section and field IDs are auto-generated by the provider whenever they come
// through as empty (see toModelSectionField, toModelSectionFieldMap and
// toModelSections in state_to_model.go). UseNonNullStateForUnknown only skips
// locking in the state value when it's null, so an id already recorded as ""
// gets planned as "" too - then Create/Update assigns it a real, non-empty
// id, and Terraform reports "Provider produced inconsistent result after
// apply" because the applied value doesn't match what was planned.
//
// Treating a stored "" the same as null lets that one-time transition happen
// as an ordinary computed update instead of a hard error. Once an id is a
// real non-empty value, this modifier preserves it exactly like
// UseNonNullStateForUnknown does.
func UseGeneratedIDForUnknown() planmodifier.String {
	return useGeneratedIDForUnknown{}
}

type useGeneratedIDForUnknown struct{}

func (m useGeneratedIDForUnknown) Description(_ context.Context) string {
	return "Once set to a non-null, non-empty value, the value of this attribute in state will not change."
}

func (m useGeneratedIDForUnknown) MarkdownDescription(_ context.Context) string {
	return m.Description(context.Background())
}

func (m useGeneratedIDForUnknown) PlanModifyString(_ context.Context, req planmodifier.StringRequest, resp *planmodifier.StringResponse) {
	// Do nothing if the state value is null or empty - the provider will
	// assign it a real id, so leave the planned value unknown instead of
	// locking in a value that Create/Update is guaranteed to change.
	if req.StateValue.IsNull() || req.StateValue.ValueString() == "" {
		return
	}

	// Do nothing if there is a known planned value.
	if !req.PlanValue.IsUnknown() {
		return
	}

	// Do nothing if there is an unknown configuration value, otherwise interpolation gets messed up.
	if req.ConfigValue.IsUnknown() {
		return
	}

	resp.PlanValue = req.StateValue
}
